
from pandas import *
data = read_csv("NVM.csv")
"""
X.1	X	X1	obj_buurt_ID	BWPER	CATEGORIE	DATUM_AANMELDING	DATUM_AFMELDING	LAATSTVRKOOPPR	ERFPACHT_TONEN	GARAGE	GED_VERHUURD	GEMEUBILEERD	HUISNUMMER	HUISNUMMERTOEVOEGING	INHOUD	INPANDIG	ISBELEGGING	ISNIEUWBOUW	ISOL	KELDER	KOOPCOND	KWALITEIT	LAATSTVRHUURPR	LAATSTVRKOOPPR1	LAATSTVRKOOPPRM2	LIFT	LIGCENTR	LIGMOOI	LIGDRUKW	LOOPT	M2	MONUMENT	MONUMENTAAL	NBALKON	NKAMERS	NVERDIEP	NVMCIJFERS	NWC	ONBI	ONBU	OORSPRVRKOOPPR	OORSPRVRKOOPPRM2	OPENH	PARKEER	PERCEEL	obj_pc4_ID	obj_pc6_ID	POSTCODE	PROCVERSCHIL	SCHUUR	SOORTAPP	SOORTHUIS	SOORTWONING	SOORTDAK	STATUS	STRAATNAAM	TRANSACTIEPRIJS	TRANSACTIEPRIJSM2	TUIN_OPP	TUINLIG	TYPE	VERKOOPCOND	VERW	VLIER	obj_wijk_ID	WOONKA	WOONOPP	WOONPLAATS	ZOLDER	woningvoorraad	Hypotheekrente..	bbp..miljard.	bevolking..ZH.	GEMEENTE	Close

"""
streetnames = data['STRAATNAAM'].tolist()

print('streetnames', streetnames)